#spring.datasource.url=jdbc:h2:mem:flowable-db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:postgresql://localhost:5432/flowable?currentSchema=flowable
spring.datasource.username=flowable
spring.datasource.password=flowable
spring.datasource.driver-class-name=org.postgresql.Driver
flowable.database-schema-update=true
flowable.async-executor-activate=true
flowable.check-process-definitions=true
logging.level.root=INFO
logging.level.org.thymeleaf.spring6.processor=ERROR
logging.level.org.thymeleaf=ERROR
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
server.port=9080